### ISSUE TITLE
Overflowed with example code

### ISSUE THREAD

**Issue by fabioselau077** [tailoristic/floating_navigation_bar#1]
Hello, using this example return Overflowed
FloatingNavigationBar
You can inspect this widget using the 'Inspect Widget' button in the VS Code notification.
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
<img width="387" alt="image" src="https://user-images.githubusercontent.com/57275833/206803406-1a8fe729-d7da-49f8-ac13-7ce5eb3bfefc.png">

**Comment by tailoristic** [comment]
Thanks for the PR.
